### ISSUE TITLE
How to extract prediction from this model? 

### ISSUE THREAD

**Issue by saralee48** [guoyang9/NCF#11]
Hi, sorry to bother you. I'm trying to extract useful prediction from this model. For example, a prediction I'm trying to get is: for movie ID 123 and user ID 456, I want to know how likely the user will like this movie. Another way could be returning 10 top item for a particular user ID. I would really appreciate your help!

**Comment by guoyang9** [comment]
This repo is mainly built to reimplement the NCF paper with Pytorch. I'm not sure the candidate item set you meant. If the candidate item set is the 100 randomly selected items as mentioned in the original paper, the top-10 items can be easily obtained via https://github.com/guoyang9/NCF/blob/89ff06ffcd2bca6bb773b54925265c208a28d318/evaluate.py#L27. However, if you want to recommend the top-10 items based on the whole item set, I would like to suggest you adjust the data preprocessing step under this situation.

**Comment by saralee48** [comment]
Thank you for your suggestions. I would further adjust my data processing step in order to recommend the top-10 items based on the entire item set!
