### ISSUE TITLE
Concatenation of user and item embeddings

### ISSUE THREAD

**Issue by Aroize** [guoyang9/NCF#15]
Hi! I am a newbee in recommendation systems and machine learning. After reading the paper and watching your implementation I have a question - does NeuMF have a limitation of dimensionality of users and items? I'm not able to concat embeddings with parameters (for example) 
```
user_num = 3
item_num = 2
RuntimeError                              Traceback (most recent call last)
<ipython-input-129-98d01e5c09d2> in <module>
      2 i_count = 2
      3 ncf = NCF_stolen(u_count, i_count, 12, num_layers=2, dropout=0.0, model='NeuMF-end')
----> 4 ncf(torch.zeros(u_count, dtype=torch.long), torch.zeros(i_count, dtype=torch.long))

~/env3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

<ipython-input-118-10286f7471cc> in forward(self, user, item)
     93                         embed_user_GMF = self.embed_user_GMF(user)
     94                         embed_item_GMF = self.embed_item_GMF(item)
---> 95                         output_GMF = embed_user_GMF * embed_item_GMF
     96                 if not self.model == 'GMF':
     97                         embed_user_MLP = self.embed_user_MLP(user)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0
```
Thx for feedback!

**Comment by guoyang9** [comment]
I don't not fully understand what kind of issue you encountered based on the provided code slice. 

If you want to concatenate the user and item embeddings together and then pass them through an MLP layer, I would suggest to firstly change the input dimension of the MLP layer.

**Comment by Aroize** [comment]
Actually, I've failed with understanding of Embeddings in PyTorch and Embeddings in paper. In paper as input was passed one-hot encoding to layer, so there were problems with dimensions. But nn.Embedding is able to provide vector only for a single value as index of item or user. If I'm wrong, please correct me.
PS: Sorry for waisting your time, but your code helped me to understand the theme a little bit more, what I want to thank you!
