### ISSUE TITLE
a error about use pretraining

### ISSUE THREAD

**Issue by JingsenZhang** [guoyang9/NCF#18]
hi，
when i use NeuMF model with pretraining, a error arises like this:

AttributeError: Can't get attribute 'GMF' on <module '__main__' from 'NeuMF.py'>
![image](https://user-images.githubusercontent.com/36886184/90467387-b04cb980-e146-11ea-8671-c618c37e4dd0.png)

in code :
![image](https://user-images.githubusercontent.com/36886184/90467432-c5294d00-e146-11ea-89a7-fe0d81ec5d8c.png)

do you know how to solve it?  thank you very much!

**Comment by guoyang9** [comment]
Pre-training of NeuMF requires to train GML and MLP models first. 
Both models will be saved and reloaded when using them to initialize NeuMF.

**Comment by JingsenZhang** [comment]
As you said, i have trained the GMF and MLP, so it didn't trigger the 'assert' 
But when run the torch.load(GMF) this error arose.

**Comment by guoyang9** [comment]
Do not change the code when loading pre-trained models.

If this error occurs again, roll back this repo to the original version because you have made some mistakes when you tried to update it.
