### ISSUE TITLE
Do your code with pytorch  have the 

### ISSUE THREAD

**Issue by ZX-USER** [guoyang9/NCF#19]
Do your code have the step of pre_training? I didn't find it,so when i use the NeuMf-pre ,it accur the error that lack of GMF model.Can you show me the step of Pre_training,thankyou

**Comment by guoyang9** [comment]
1) Set model name in `config.py` to be `GMF`, train and autosave the best `GMF` model.
2) Set model name in `config.py` to be `MLP`, train and autosave the best `MLP` model.
3) Set model name in `config.py` to be `NeuMF-pre`, and then you can autoload the pre-trained model.
