### ISSUE TITLE
No such file or directory: './Data/data.npy'

### ISSUE THREAD

**Issue by loveJasmine** [guoyang9/NCF#2]
mldl@ub1604:~/ub16_prj/NCF/pytorch$ python3 main.py --batch_size=128 --lr=0.00001 --embed_size=1
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    data = np.load(os.path.join(DATA_PATH, 'data.npy')).item()
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './Data/data.npy'
mldl@ub1604:~/ub16_prj/NCF/pytorch$

**Comment by guoyang9** [comment]
See the new code.
