### ISSUE TITLE
Why I use  the same code and parameters,the result is not as good as yours?

### ISSUE THREAD

**Issue by ZX-USER** [guoyang9/NCF#20]
Why I use  the same code and parameters,the result is not as good as yours?

**Comment by guoyang9** [comment]
Post your running scripts and results first, please?

**Comment by ZX-USER** [comment]
![image](https://user-images.githubusercontent.com/72249158/99865160-d0c35e80-2be2-11eb-92e1-2f1a3bef6642.png)

**Comment by ZX-USER** [comment]
![image](https://user-images.githubusercontent.com/72249158/99865192-fa7c8580-2be2-11eb-9e61-a4712670bdbc.png)

**Comment by ZX-USER** [comment]
I only run the two sofar,the result of NeuMF-end is no beeter than GMF

**Comment by guoyang9** [comment]
Have you read the original paper and the README of this repo?
