### ISSUE TITLE
another issue 

### ISSUE THREAD

**Issue by ZX-USER** [guoyang9/NCF#21]
And another issue is that when i use the model as MIP and GMF,the model isn't saved?
Do you know the reason?
With the issue ,i can't use the model as NeuMF-pre ,the issue is that can't find GMF

**Comment by guoyang9** [comment]
If you set the `out` flag to be True, the model will auto save in this [line](https://github.com/guoyang9/NCF/blob/89ff06ffcd2bca6bb773b54925265c208a28d318/main.py#L134).

Please, very very carefully read the repo first before you post another issue :)
