### ISSUE TITLE
向量生成

### ISSUE THREAD

**Issue by Shodowelf** [guoyang9/NCF#23]
你好，
请问如果我想通过user与item的交互数据来生成user的factor与item的factor请问这个在这个代码中是哪里体现出来的？

**Comment by guoyang9** [comment]
见[model.py](https://github.com/guoyang9/NCF/blob/master/model.py) 93 - 109。
user和item的factor存在四个embed矩阵里，看你想要哪一个了。

**Comment by Shodowelf** [comment]
谢谢
