### ISSUE TITLE
 negative samples should be different in each train epoch

### ISSUE THREAD

**Issue by KylinA1** [guoyang9/NCF#4]
1. negative samples in training data should be different in each training epoch, otherwise it will  overfitting. 
2.  when you sampling negative items to get training dataset, the positive item in test dataset should not be included in user's positive dictionary, it also have chance to become a negative item in training data.

- All above you can find that in the official implementation.

**Comment by guoyang9** [comment]
For your first question, I should update the [add_negative()](https://github.com/guoyang9/NCF/blob/c419a96c032ca494f4ab0ca3e10244aa7209199d/pytorch/NCF_input.py#L88) function inside the training data construction. Further modification will be provided. Thanks for commenting.

For the second question, as in a real scenario, all the items that are not purchased by this user should be in the candidate negative item set. Therefore, I do slightly not agree with the Xiangnan He on this point.

**Comment by KylinA1** [comment]
Thank you for your kind notes.
I think we share the same opinion - "
all the items that are not purchased by this user should be in the candidate negative item set", what exactly the official implementation did.
In you implementation, there are two dictionaries - user_bought, which contains test positive one, user_negative where you sampling negative items from.
Actually, the test positive item should be in the user_negative dictionary other than user_bought.

**Comment by guoyang9** [comment]
Yeah, that is really a bad issue. I will modify this. Thanks!

**Comment by guoyang9** [comment]
I fixed this bug, check the new version.
