### ISSUE TITLE
The negative sampling method has a great influence on performance

### ISSUE THREAD

**Issue by familyld** [guoyang9/NCF#6]
I found that the negative sampling method used in your code is without replacement:

```
np.random.choice(user_negative[user], size=numbers, replace=False).tolist()
```
 
Although this method takes more time (around 300s for generating negative samples for the training set), it can greatly improve the performance. While in the original implementation of NCF, the author uses sampling with replacement:

```python
def get_train_instances(train, num_negatives):
    trainData = []
    num_users = train.shape[0]
    for (u, i) in train.keys():
        # positive instance
        trainData.append([u, i, 1])
        # negative instances
        for t in range(num_negatives):
            j = np.random.randint(num_items)
            while (u, j) in train.keys():
                j = np.random.randint(num_items)
            trainData.append([u, j, 0])
    return np.array(trainData)
```

From my experiments, using such strategy in your code seriously decrease the performance. Also, if you use [the provided test data](https://github.com/hexiangnan/neural_collaborative_filtering/blob/master/Data/ml-1m.test.negative) to test the model , you will find that the performance is pretty poor. I'm not quite sure how the provided test data is generated, but the performance should not be that bad. 

I tried to use pytorch to reproduce the results on my own before, but it performs much worse than using keras with tensorflow as the backend. Then I found your implementation and did some experiments, but it turns out the performance is unsatisfactory too. It will be great if you can test on the provided test data and do some further experiments.  Thanks.

**Comment by guoyang9** [comment]
The negative sampling is truly a bad problem. I will correct this in further version. Actually, the test data should be all the items that are not purchased by the target user. However, it would cost too much time if you do so and Xiangnan randomly sampled the test data as shown in the original paper (as far as I know, they didn't have enough resources to work on this setting, but now the hardware conditions are better).  It doesn't matter only if you test for all baselines on the same dataset setting.

**Comment by familyld** [comment]
Look forward to your future version!

**Comment by guoyang9** [comment]
The code has been updated.
