### ISSUE TITLE
AssertionError: lack of GMF model

### ISSUE THREAD

**Issue by zijinchen** [guoyang9/NCF#8]
你好，运行了下您的代码，报了这个错误，查看下config.py文件，发现有个‘./models’的路径，这个后面写的有GMF.pth,MLP.pth,NeuMF.pth, 这些文件您是不是没有上传呢，谢谢！

**Comment by guoyang9** [comment]
default的model是用的NeuMF-pre (用了pre-trained weights），所以必须要先train完GMF和MLP，如果不想用pre-train，可以直接 set model=NeuMF-end (end-to-end training).

**Comment by zijinchen** [comment]
非常感谢您的回复，不好意思，我是名初学者，能听懂您的意思，具体怎么操作有点困难，我希望先按照您上传的文件简单运行一下，然后学习学习，发现几个小问题：
1.运行语句 python main.py --batch_size=256 --lr=0.001 --embed_size=16，报错说embed_size参数不存在，我是做删除处理的
2.报错说Data文件没有，所以我去论文github项目下载了Data文件，添加到了您的文件夹里
3.报错这句代码assert os.path.exists(config.GMF_model_path), "lack of GMF model"有问题，问题是AssertionError: lack of GMF model，所有我查看了config.py文件，以为和之前Data文件一样是缺少，
所以向您询问了下，说实话，接下来我不知怎么处理了，如果您能指点一二，我将十分感激！谢谢






------------------ 原始邮件 ------------------
发件人: "Yangyang Guo"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 下午4:45
收件人: "guoyang9/NCF"<NCF@noreply.github.com>;
抄送: "陈子晋"<994173107@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guoyang9/NCF] AssertionError: lack of GMF model (#8)




default的model是用的NeuMF-pre (用了pre-trained weights），所以必须要先train完GMF和MLP，如果不想用pre-train，可以直接 set model=NeuMF-end (end-to-end training).

**Comment by zijinchen** [comment]
非常感谢您的回复，不好意思，我是名初学者，能听懂您的意思，具体怎么操作有点困难，我希望先按照您上传的文件简单运行一下，然后学习学习，发现几个小问题：
1.运行语句 python main.py --batch_size=256 --lr=0.001 --embed_size=16，报错说embed_size参数不存在，我是做删除处理的
2.报错说Data文件没有，所以我去论文github项目下载了Data文件，添加到了您的文件夹里
3.报错这句代码assert os.path.exists(config.GMF_model_path), "lack of GMF model"有问题，问题是AssertionError: lack of GMF model，所有我查看了config.py文件，以为和之前Data文件一样是缺少，
所以向您询问了下，说实话，接下来我不知怎么处理了，如果您能指点一二，我将十分感激！谢谢

**Comment by guoyang9** [comment]
1) embed_size是我写错了，马上更正，应该是factor_num;
2) Data文件我readme里说了，要去Xiangnan He那下载；
3) 最简单的解决方式，不用pre-train，具体参考Xiangnan WWW17 paper，config.py中设置model='NeuMF-end'.
