### ISSUE TITLE
GMF better than BPR

### ISSUE THREAD

**Issue by KylinA1** [guoyang9/NCF#9]
Hi, 

Compared to the result of your BPR model,  GMF achieve better performance.
Is it reasonable

**Comment by guoyang9** [comment]
I guess the BPR you mean is the final NeuMF model. Under the setting I experimented (i.e., factor number - 32, MLP layers -3), better performance of GMF can be observed, yes. And this pytorch-version GMF even outperforms the NeuMF model as reported in the original paper. 

The reason behind this is that in many occasions, as I found, less parameters and simpler modules can perform reasonably good. But I haven't tried other settings in NCF, maybe larger embedding size leads to worse performance of GMF. 

Overall, I am sure there is no difference between Xiangnan's repo and this pytorch one, especially the initialization method, which takes me a while to figure out them. Other reasons making this happen is maybe the background mechanism behind Keras and Pytorch.

**Comment by KylinA1** [comment]
> I guess the BPR you mean is the final NeuMF model. Under the setting I experimented (i.e., factor number - 32, MLP layers -3), better performance of GMF can be observed, yes. And this pytorch-version GMF even outperforms the NeuMF model as reported in the original paper.
> 
> The reason behind this is that in many occasions, as I found, less parameters and simpler modules can perform reasonably good. But I haven't tried other settings in NCF, maybe larger embedding size leads to worse performance of GMF.
> 
> Overall, I am sure there is no difference between Xiangnan's repo and this pytorch one, especially the initialization method, which takes me a while to figure out them. Other reasons making this happen is maybe the background mechanism behind Keras and Pytorch.

Thanks for your kind notes.
BPR is another repo that you implemented.
Typically, As I observed , direct inner product of two embedding vectors performs better than MLP.

**Comment by guoyang9** [comment]
> > I guess the BPR you mean is the final NeuMF model. Under the setting I experimented (i.e., factor number - 32, MLP layers -3), better performance of GMF can be observed, yes. And this pytorch-version GMF even outperforms the NeuMF model as reported in the original paper.
> > The reason behind this is that in many occasions, as I found, less parameters and simpler modules can perform reasonably good. But I haven't tried other settings in NCF, maybe larger embedding size leads to worse performance of GMF.
> > Overall, I am sure there is no difference between Xiangnan's repo and this pytorch one, especially the initialization method, which takes me a while to figure out them. Other reasons making this happen is maybe the background mechanism behind Keras and Pytorch.
> 
> Thanks for your kind notes.
> BPR is another repo that you implemented.
> Typically, As I observed , direct inner product of two embedding vectors performs better than MLP.

Sorry for the misunderstanding. 
It depends. Pair-wise learning is not always dominant in all conditions.
